=== LuisHenriqueAlvesdeSousa/ProyectoFinal/Fase-2/XML/UltimaJornada/ultimaJornada.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="ultimaJornada" type="tultimaJornada"/>

<xs:complexType name="tultimaJornada">
                              <xs:sequence>
                                          <xs:element name="info" type="tinfo"/>
                              </xs:sequence>
</xs:complexType>

<xs:complexType name="tinfo">
                              <xs:sequence>
                                          <xs:element name="torneo" type="ttorneo"/>
                              </xs:sequence>
</xs:complexType>

<xs:complextype name="ttorneo">
                              <xs:sequence>
                                          <xs:element name="jornada" type="tjornada"/>
                              </xs:sequence>
<xs:complextype>

<xs:complexType name="tjornada">
                              <xs:sequence>
                                          <xs:element name="partido" type="tpartido" minOccurs="1" maxOccurs="unbounded"/>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:positiveInteger"/>
                              <xs:attribute name="fecha" type="xs:date"/>
</xs:complexType>

<xs:complexType name="tpartido">
                              <xs:sequence>
                                          <xs:element name="equipo" type="tequipo" minOccurs="2" maxOccurs="2"/>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:positiveInteger"/>
                              <xs:attribute name="hora" type="xs:time"/>
</xs:complexType>


<xs:complexType name="tequipo">
                              <xs:sequence>
                                            <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                            <xs:element name="pais" type="xs:string" minOccurs="1" maxOccurs="1"/>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:positiveInteger"/>
                              <xs:attribute name="estado" type="testado"/>
</xs:complexType>

<xs:simpleType name="testado">
                            <xs:restriction base="xs:string">
                                                      <xs:enumeration value="clasificado"/>
                                                      <xs:enumeration value="eliminado"/>
                            </xs:restriction>
</xs:simpleType>




</xs:schema>

=== LuisHenriqueAlvesdeSousa/ProyectoFinal/Fase-2/XML/UltimaJornada/ultimaJornada_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<ultimaJornada xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
                xs:noNamespaceSchemaLocation = "ultimaJornada.xsd">
            <info>
                <torneo estado="CERRADO">
                        <jornada id="0001" fecha="2021-05-05">
                                  <partido id="0001" hora="17:30:00">
                                                    <equipo id="0001">
                                                                    <nombre>Astralis</nombre>
                                                                    <pais>Belgica</pais>
                                                    </equipo>
                                                    <equipo id="0002">
                                                                    <nombre>Giant</nombre>
                                                                    <pais>Rusia</pais>
                                                    </equipo>
                                  </partido>
                                  <partido id="0002" hora="18:30:00">
                                                    <equipo id="0003">
                                                                    <nombre>G2A</nombre>
                                                                    <pais>Espana</pais>
                                                    </equipo>
                                                    <equipo id="0004">
                                                                    <nombre>Cloud9</nombre>
                                                                    <pais>Polonia</pais>
                                                    </equipo>
                                  </partido>
                                  <partido id="0003" hora="19:30:00">
                                                    <equipo id="0005">
                                                                    <nombre>Aestethics</nombre>
                                                                    <pais>Italia</pais>
                                                    </equipo>
                                                    <equipo id="0006">
                                                                    <nombre>Naranjito</nombre>
                                                                    <pais>Venezuela</pais>
                                                    </equipo>
                                  </partido>
                                  <partido id="0004" hora="20:30:00">
                                                    <equipo id="0007">
                                                                    <nombre>Goku</nombre>
                                                                    <pais>Japon</pais>
                                                    </equipo>
                                                    <equipo id="0008">
                                                                    <nombre>Shin</nombre>
                                                                    <pais>China</pais>
                                                    </equipo>
                                  </partido>
                        </jornada>
                </torneo>
            </info>
</ultimaJornada>
