=== LuisHenriqueAlvesdeSousa/ProyectoFinal/Fase-2/XML/UltimaJornada/ultimaJornada.dtd
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< refs/remotes/origin/lineaRober
=======
<!ELEMENT torneo (jornada+)>
<!ATTLIST torneo estado (abierto|cerrado) "abierto">
>>>>>>> lineaRober
<!ELEMENT jornada (partido+)>
<!ATTLIST jornada id CDATA #REQUIRED>
<!ATTLIST jornada fecha CDATA #REQUIRED>
<!ELEMENT partido (equipo+)>
<!ATTLIST partido id CDATA #REQUIRED>
<!ATTLIST partido hora CDATA #REQUIRED>
<!ELEMENT equipo (nombre, pais)>
<!ATTLIST equipo id CDATA #REQUIRED>
<!ATTLIST equipo puntuacion CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
=======
<!ELEMENT jornada (partido+)>
<!ATTLIST jornada id CDATA #REQUIRED>
<!ATTLIST jornada fecha CDATA #REQUIRED>
<!ELEMENT partido (equipo+)>
<!ATTLIST partido id CDATA #REQUIRED>
<!ATTLIST partido hora CDATA #REQUIRED>
<!ELEMENT equipo (nombre, pais)>
<!ATTLIST equipo id CDATA #REQUIRED>
<!ATTLIST equipo estado (clasificado|eliminado) "clasificado">
<!ELEMENT nombre (#PCDATA)>
>>>>>>> organizar xml
=======
<!ELEMENT jornada (partido+)>
<!ATTLIST jornada id CDATA #REQUIRED>
<!ATTLIST jornada fecha CDATA #REQUIRED>
<!ELEMENT partido (equipo+)>
<!ATTLIST partido id CDATA #REQUIRED>
<!ATTLIST partido hora CDATA #REQUIRED>
<!ELEMENT equipo (nombre, pais)>
<!ATTLIST equipo id CDATA #REQUIRED>
<!ATTLIST equipo estado (clasificado|eliminado) "clasificado">
<!ELEMENT nombre (#PCDATA)>
>>>>>>> main
<!ELEMENT pais (#PCDATA)>

=== LuisHenriqueAlvesdeSousa/ProyectoFinal/Fase-2/XML/UltimaJornada/ultimaJornada_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE torneo SYSTEM "ultimaJornada.dtd">
<torneo estado="cerrado">
               <jornada id="0001" fecha="05-05-2021">
                                 <partido id="0001" hora="17:30:00">
                                                   <equipo id="0001" puntuacion="21">
                                                                   <nombre>Astralis</nombre>
                                                                   <pais>Belgica</pais>
                                                   </equipo>
                                                   <equipo id="0002" puntuacion="10">
                                                                   <nombre>Giant</nombre>
                                                                   <pais>Rusia</pais>
                                                   </equipo>
                                 </partido>
                                 <partido id="0002" hora="18:30:00">
                                                   <equipo id="0003" puntuacion="33">
                                                                   <nombre>G2A</nombre>
                                                                   <pais>Espana</pais>
                                                   </equipo>
                                                   <equipo id="0004" puntuacion="55">
                                                                   <nombre>Cloud9</nombre>
                                                                   <pais>Polonia</pais>
                                                   </equipo>
                                 </partido>
                                 <partido id="0003" hora="19:30:00">
                                                   <equipo id="0005" puntuacion="24">
                                                                   <nombre>Aestethics</nombre>
                                                                   <pais>Italia</pais>
                                                   </equipo>
                                                   <equipo id="0006" puntuacion="2">
                                                                   <nombre>Naranjito</nombre>
                                                                   <pais>Venezuela</pais>
                                                   </equipo>
                                 </partido>
                                 <partido id="0004" hora="20:30:00">
                                                   <equipo id="0007" puntuacion="15">
                                                                   <nombre>Goku</nombre>
                                                                   <pais>Japon</pais>
                                                   </equipo>
                                                   <equipo id="0008" puntuacion="64">
                                                                   <nombre>Shin</nombre>
                                                                   <pais>China</pais>
                                                   </equipo>
                                 </partido>
               </jornada>
  </torneo>
