=== LuisHenriqueAlvesdeSousa/ProyectoFinal/xml/ClasificacionGeneral_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="clasificacion" type="tclasificacion"/>
  
  
<xs:complexType name="tclasificacion">
                              <xs:sequence>
                                                      <xs:element name="jornada" type="tjornada" minOccurs="1" maxOccurs="unbounded"/>
                              </xs:sequence>
</xs:complexType>

<xs:complexType name="tjornada">
                              <xs:sequence>
                                          <xs:element name="equipo" type="tequipo" minOccurs="1" maxOccurs="unbounded"/>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:positiveInteger"/>
                              <xs:attribute name="fecha" type="xs:date"/>
</xs:complexType>

<xs:complexType name="tequipo">
                              <xs:sequence>
                                            <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                            <xs:element name="pais" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                            <xs:element name="jugador" type="tjugador" minOccurs="1" maxOccurs="6"/>
                              </xs:sequence>
                              <xs:attribute name="estado" type="testado"/>
</xs:complexType>

<xs:complexType name="tjugador">
                              <xs:sequence>
                                                      <xs:element name="nickname" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                      <xs:element name="rol" type="xs:string" minOccurs="1" maxOccurs="1"/>
                              </xs:sequence>
</xs:complexType>

<xs:simpleType name="testado">
                            <xs:restriction base="xs:string">
                                                      <xs:enumeration value="clasificado"/>
                                                      <xs:enumeration value="eliminado"/>
                            </xs:restriction>
</xs:simpleType>




</xs:schema>

=== LuisHenriqueAlvesdeSousa/ProyectoFinal/xml/ClasificacionGeneral.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clasificacion SYSTEM "ClasificacionGeneral_DTD.dtd">
<clasificacion  xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "ClasificacionGeneral_XSD.xsd">
                          <jornada id="001" fecha="2021-08-05">
                                            <equipo estado="clasificado">
                                                            <nombre>Astralis</nombre>
                                                            <pais>Polonia</pais>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador> 
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                            </equipo>
                                            <equipo estado="clasificado">
                                                            <nombre>Natus Vincere</nombre>
                                                            <pais>Rusia</pais>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador> 
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                            </equipo>
                                            <equipo estado="clasificado">
                                                            <nombre>Virtus Pro</nombre>
                                                            <pais>Rusia</pais>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador> 
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                            </equipo>
                                            <equipo estado="clasificado">
                                                            <nombre>Astralis</nombre>
                                                            <pais>Polonia</pais>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador> 
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                                            <jugador>
                                                                              <nickname></nickname>
                                                                              <rol></rol>
                                                            </jugador>
                                            </equipo>
                          </jornada>
</clasificacion>
